substitutions:
  device_name: "llum-ventilador-marcscave"
  friendly_name: "llum-ventilador-marcscave"
  output_name_1: "Output 1"
  output_name_2: "Output 2"
  input_name_1: "Input 1"
  input_name_2: "Input 2"

packages:

  shelly-plus-2: !include ../hardware/shelly-plus-2.yaml
  debug: !include ../common/debug.yaml
  reset: !include ../common/reset.yaml
  time: !include ../common/time.yaml
  web-server: !include ../common/web-server.yaml
  mqtt: !include ../common/mqtt.yaml

  wifi: !include
    file: ../common/wifi.yaml
    vars:
      device_name: ${device_name}

output:
  - platform: gpio
    id: "relay_output_1"
    pin: GPIO12
  - platform: gpio
    id: "relay_output_2"
    pin: GPIO13

switch:
  - platform: output
    id: "relay_1"
    name: "${output_name_1}"
    output: "relay_output_1"
  - platform: output
    id: "relay_2"
    name: "${output_name_2}"
    output: "relay_output_2"

binary_sensor:

  # Input 1
  - platform: gpio
    name: "${input_name_1}"
    id: "input_1"
    pin: GPIO5
    filters:
      - delayed_on_off: 50ms
    on_multi_click:

      # Single click (short press) - toggle relay_1
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${device_name} Button - TAP"
          - switch.toggle: relay_1

      # Hold (long press) - turn on relay_2, then off after 60 minutes
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${device_name} Button - HOLD"
          - switch.toggle: relay_2
          - if:
              condition:
                switch.is_on: relay_2
              then:
                - delay: 60min
                - switch.turn_off: relay_2
    internal: true

  # Input 2
  - platform: gpio
    id: "input_2"
    name: "${input_name_2}"
    pin: GPIO18
    filters:
      - delayed_on_off: 50ms
    on_press:
      then:
        - switch.toggle: relay_2
    internal: true
